### ISSUE TITLE
feature request: bewegingssensor - flow card for lux valu

### ISSUE THREAD

**Issue by Heki2017** [athombv/com.fibaro#169]
Dear reader,

The fibaro 'bewegingssensor' app supports a trigger flow card for change in 'helderheid', however there is no flow card 'helderheid (not) greater' which forces to store the value in an additional flow in a BL variable before being used. Is it possible to add such a flowcard (maybe even more in general for all class: Sensors with Type: number)
![schermafbeelding 2017-08-27 om 11 11 41](https://user-images.githubusercontent.com/26427299/29748515-989128d0-8b18-11e7-9c63-7168e8011b0e.png)

**Comment by caseda** [comment]
There is no need for such a flow card on the device itself, as such a thing is called "logic" and thus is handled by the "logic" cards:
![screenie](https://user-images.githubusercontent.com/2565450/29748724-1cec7712-8b1c-11e7-89ba-532bad696ee8.jpg)

**Comment by Heki2017** [comment]
Thanks very much for this info. I was not aware of that. Sorry for posting the issue. Kind regards Hedzer

**Comment by mruiter** [comment]
But it would be nice if it was following the standards aka lux and not helderheid.

There have been multiple aka more then 50 questions about it not working because people use the default lux in the forum and on slack it also passed many times.
I would think the lux just like almost all other zwave devices would be nicer to use then the helderheid.

but thats just my 2 cents..

Verstuurd vanaf mijn iPad

**Comment by caseda** [comment]
Lux is just a way to adres brightness? Just like meter is for length. 

And homey is flowing the lux standard..? Or am I miss interpreting you now..
