### ISSUE TITLE
Motion sensor (Z-wave plus) not working ok

### ISSUE THREAD

**Issue by Rido** [athombv/com.fibaro#210]
Good morning,

Yesterday I installed 2 new Fibaro motion sensors Z-wave plus, but I have some problems with these sensors. The LED mode & lux reporting LED does not work very well.

I tried to disable the LED but with each movement it flashes blue. 

And the lux monitor isn't reporting very well. I attached a image of the lux stats of today. These should have changed multiple time this morning because the lamps switched on first and after a while I opened the curtains.

Homey is running on version **1.5.8**

**Settings (for both the same):**
![image](https://user-images.githubusercontent.com/1889864/37449782-e53d5856-282b-11e8-91ea-e9e3a80659ff.png)

**Lux stats:**
![image](https://user-images.githubusercontent.com/1889864/37449988-91341500-282c-11e8-9baf-67ece598e3b7.png)

Thanks!

**Comment by Rido** [comment]
Any update regarding this issue?

**Comment by MatthewWaanders** [comment]
It’s very much a work in process as it is now and I wouldn’t recommend you to install it just yet.

I can’t provide any timelines or deadlines for bringing out the update, it’s one of our bigger apps and you never know what you run in to, I’ll keep you up to date!

**Comment by TedTolboom** [comment]
@rido can you try the following:
When changing one of the parameters, before pressing the save button, move the sensor in close proximity of Homey and tripple click the B-button of the sensor so that the LED will light up blue... 
Directly afterwards press the save button.
It should say: settings updated...
It might be that in previous attempts the communication of new parameter values failed or did not yet take place due to the wake up interval

**Comment by MatthewWaanders** [comment]
I'm closing this issue for now as it should be fixed with the SDK2 update, which we're working on and we're making good progress. 
It will take a short while before release and I hope you are able to wait for that!
