### ISSUE TITLE
Fibaro thermostat (FGT-001) temperature/noise issue

### ISSUE THREAD

**Issue by Martijnjongeneel** [athombv/com.fibaro#264]
I have connected a fibaro thermostat and connected with homey. The crane will switch on and off between 15 and 30 minutes.
Even when I put the demand temperature at 10 degrees, the radiator stays a little warm and the tap keeps going in and out every now and then.
The crane I calibrated several times but this does not matter.
I also used the regular app of fibaro and the beta version but this also makes no difference.
I do use an external heat sensor that comes with this.

Can someone help me with this?

**Comment by jeroenvollenbrock** [comment]
We're sorry to hear your Fibaro Thermostat is not functioning as expected. Please note that this however is a bug tracker and not a regular support channel. The fastest way to get direct support is by sending an e-mail to support@athom.com.

**Comment by synegic** [comment]
@Martijnjongeneel the problem here is the automatic setpoint algorithm used by Fibaro. Nothing to do with Homey. To solve this, thermostat_mode support has to be added to the device. I just created a pull request (#276) for this. You should put your thermostat head into 'off', 'cooling' or 'heating' mode if you want it to stop turning all the time.
