### ISSUE TITLE
Dimmer 1 (FDG-211) S2 input has no flow triggers

### ISSUE THREAD

**Issue by irritanterik** [athombv/com.fibaro#32]
I connected double momentary switches to my build in dimmer modules, so the second button can control other devices or scenes from flows or associations. 
After successfully pairing the dimmer module to Homey there are no flow cards available for S2 related events.

**Comment by RobinBol** [comment]
S2 button functionality has been added.

**Comment by irritanterik** [comment]
Awesome!
@RobinBol  Does it require specific parameter settings?

**Comment by RobinBol** [comment]
I think so, take a look at the PR that added it:
https://github.com/athombv/com.fibaro/pull/29

**Comment by irritanterik** [comment]
@swttt can you confirm?

**Comment by swttt** [comment]
@irritanterik only works for dimmer 2, not the first version. Dimmer 2 has the ability to set the s2 as basic onoff command class, since the s1 uses multilevel this doesn't conflict, and any onoff command send from the dimmer results in a flow start.

But since you asked about the Dimmer 1, no sorry not possible. Tried it in every way, but weejewel needs to add support for scene_activation.

**Comment by swttt** [comment]
Seems my PR description isn't 100 percent clear about that, sorry!

**Comment by irritanterik** [comment]
Thanks for you comment. @RobinBol please reopen this issue because it's about the dimmer 1.

**Comment by swttt** [comment]
@RobinBol This could as well be added to the general Athom issues tho. Since its not only fibaro related. Others use the scene_activation class as well.

**Comment by RobinBol** [comment]
The coming Fibaro app update will bring advanced Flow card functionality for both S1 and S2.
