### ISSUE TITLE
FGBP-101 Fibaro Button not supported

### ISSUE THREAD

**Issue by irritanterik** [athombv/com.fibaro#48]
Please support Fibaro Button presses, including scene activation options.

**Comment by caseda** [comment]
It's in my pull request, including scene activation

**Comment by irritanterik** [comment]
I installed your version. Works great for the push button. Thanks a lot.
Only flaw i noticed was a double trigger on the 'long hold end'.
Also would be awesome to be able to set a timeout (no retrigger for x) on the 'long hold' trigger.

**Comment by caseda** [comment]
oh i did not notice that it could triggers twice, must be because it just wanted to send the next "long hold" command, will see if i can catch that.

and what do you exactly mean with a timeout?
that it won't trigger after a certain amount? (like a max amount of triggers)
or that it not triggers (or triggers once) until you hold it for this long and then send the several pulses

**Comment by caseda** [comment]
After a lot of debugging i came across that the long press releases could even trigger for 8 times.. but have added a debouncer so it only gets send once.

**Comment by irritanterik** [comment]
Great. I will look into adding a condition card 'button is hold down''
