### ISSUE TITLE
Fibaro Motion Sensor (non Z-Wave+) doesn't reset alarm_tamper

### ISSUE THREAD

**Issue by WeeJeWel** [athombv/com.fibaro#62]
After it's triggered once, it never turns off again. Tested delay values `2` and `30`.

![screen shot 2016-10-23 at 20 22 13](https://cloud.githubusercontent.com/assets/319873/19628459/67ed5e94-995e-11e6-9a2c-31f89195e626.png)

**Comment by caseda** [comment]
The app store version is still using the old defaultConfiguration way, so a manual re-setting of the tamper operation mode is still needed. 
It is fixed in my own repository, not send as a PR yet because still working on it (fgd-212 scene activation and fgbs-001 implementation, which I can't continue on because of bugs.. )

**Comment by WeeJeWel** [comment]
@caseda which bugs are you referring to?

**Comment by caseda** [comment]
@WeeJeWel 
These 2 (/3)

Dimmer 2 (FGD-212):
https://github.com/athombv/homey/issues/1033

Universal Binary Sensor (FGBS-001):
https://github.com/athombv/homey/issues/1020

**Comment by WeeJeWel** [comment]
I'll investigate!

**Comment by RobinBol** [comment]
This should be fixed by now, after a re-include. If not please re-open this issue!
