### ISSUE TITLE
Motion Sensor zwave +: no luminance!

### ISSUE THREAD

**Issue by philsniff** [athombv/com.fibaro#7]
If you place "1" in the first group instead of in the third group the luminance is shown with a value.
Before with only group 3 and id 1 not!

**Comment by caseda** [comment]
That is correct, there is a mistake with the Z-Wave+ version code.

The id **Must** be in group 1 to make the sensor work, right now it gets automatically added to group 3. (definitely a copy/past mistake)
But this will still not change anything in the motion trigger part.

Just though of this: Try to add a "1" (homey's id) to association groups 1, 2 and 3. (2&3 are all the Z-Wave+ parts of the sensor.)

**Comment by ThaYoung1** [comment]
I have a 1 in group 1 and 3 without result. Still not working after 12 hours..

**Comment by philsniff** [comment]
1 in Group 1 and 3 doesn't fix the motion Part. Only the luminance. I will try to Put 1 in all groups als caseda wrote.

**Comment by caseda** [comment]
Motion should start working with the id in
- Group 2 (which is the Motion Sensor Z-Wave+)

If all is not working with the _motion_ add the id to
- Group 4 (which is the Motion Sensor Z-Wave (for backward compatibility))
And **remove it again** from Group 2

**Comment by philsniff** [comment]
Ok, i will try in some minutes

**Comment by philsniff** [comment]
now i have all tried out. but no motion detected!
it is a motion sensor and it doesn't track motion, lol!

luminance, temperature and battery are logged in the insights as it should.
but no motion. i have now "1" in group 1 and 2...

**Comment by philsniff** [comment]
luminance only works when i pair this zwave+ sensor with the old zwave inclusion button and change from group 3 to 1!! in the zwave+ inclusion mode there cannot activate luminance in no group!

motion doesn't work in both inclusion modes (zwave or zwave+) also with 1 in group 1 and group 2

**Comment by caseda** [comment]
I don't read if you even have tried my second option if the id in Group 2 wasn't working..
(the group 4 thingy.!)

**Comment by philsniff** [comment]
I did also tried your Second Option caseda. :-(

Didn't work.

**Comment by caseda** [comment]
BTW, just to be sure.. did you wake up the sensor after saving the settings? (triple press the button)

**Comment by philsniff** [comment]
Yes of course. Btw if you triple click the sendor is shining blue. Then i always Click one Time and the light goes of. Is this right, Or should i leave it blue? Then it goes of after a while.

**Comment by philsniff** [comment]
It would ne great if there would be a callback like "Settings set "

**Comment by caseda** [comment]
The led staying blue is a bug in the z-wave driver, it's not sending the "Pairing/Saving Done" signal, so the sensor stays in pairing/awake mode.

When you single click it you just manual stop the pairing mode (instead of the signal from homey).
When you don't click it, it will timeout, so also stopping the pairing mode but on time.

So it doesn't really matter what you do, just don't do it too soon when doing it manually.

**Comment by philsniff** [comment]
Yes so i thought also. Ok, then i made all things right. But my motion sensor with zwave plus won't realise a motion :-(

But also strange that when i pair it with the non zwave plus  inclusion mode and take the id 1 in group 1 that the luminance will work. I a littlebit confused. 

When emile said that all zwave will ne easy to pair and it Took 6 weeks and fibaro was the First App they focused why is it so bad?

**Comment by caseda** [comment]
There are just some mistakes yet in the fibaro app, when it's finished it will be easy to pair z-wave devices that have been added to the "Supported Devices" list

Just because they were busy for 6 weeks, it wasn't on the Fibaro app, it was on the Z-Wave driver
(its like the foundation of an house, without a good foundation, it will collapse)

The Fibaro app is just 2 days old now, and probably not much more before that on development
(they were finishing the new library that was communicating to the Z-Wave chip this last week mostly, which is like the cement between the bricks)

When pairing the only difference is that the "Showing how to include" of the device will change (which is the same for z-wave and z-wave+).
After that it uses the same inclusion protocol as any other z-wave pairing device and looks for, if the device is on the list of supported devices

(so for example you can choose the wall socket when including the motion sensor, it will still include it as a motion sensor, and not as a weird wall socket)
(That's also why devices that are not on the supported list, can't be included in any way or form except for a default/basic on/off device)

**Comment by philsniff** [comment]
Thank you caseda for your explaination! That is very interesting! I didn't kniw that all. Also that the fibaro app is just two days old. Maybe i was a little frustrated and unfair in my thougts. 

Sorry for that @emile.

**Comment by WeeJeWel** [comment]
Thanks, added group 1 as a default as well
